### ISSUE TITLE
Grinning Jar Bug

### ISSUE THREAD

**Issue by Poshriel** [AstroPenguin642/Replay-the-Spire#34]
I was at 11 cards for grinning jar.  Every attempt to get a card from curse with cursed key, to buying in shop, to getting it as a reward for battle.

It just shut the game off.  I just decided to restart and not grab that the next time.

**Comment by Poshriel** [comment]
There's another down as well, but I couldn't recreate the bug to know exactly what happened.

**Comment by Bospad** [comment]
i am having the same problem but found a (cheating) way to bypass it, if you instead of buying/clicking the card you want add it by using the console, the game wont crash and your grinning jar counter will count to 12 and reset.

**Comment by Daenyth** [comment]
I have a stack trace and save file with this problem https://github.com/twanvl/sts-mad-science-mod/issues/8

**Comment by twanvl** [comment]
Here is another instance of this bug: https://github.com/twanvl/sts-mad-science-mod/issues/8, along with a save file to reproduce it. 
[GrinningJar-bug.zip](https://github.com/AstroPenguin642/Replay-the-Spire/files/2194014/GrinningJar-bug.zip)

For the devs: the crash happens because:

 * `GrinningJar.onObtainCard()` is called from a `FastCardObtainEffect.update()` of buying in the shop, which in turn is called by `AbstractDungeon.update()`. This effect is a `topLevelEffect`. After this update, the FastCardObtainEffect is done.
 * This adds a new `ShowCardAndObtainEffect` for pot of greed to the `topLevelEffects`.
 * This means that `topLevelEffects` is being modified while being iterated over, causing a `ConcurrentModificationException`.

Possible solutions:
* use `effectList` instead of `topLevelEffects`, but that probably breaks in the other case, where the original card was obtained via a `ShowCardAndObtainEffect`.
* add the obtain effect to the ActionManager, but that probably only works during combat
* Best solution: Just increment the counter in `GrinningJar.onObtainCard`, and add the pot of greed in `GrinningJar.update()`.

**Comment by kiooeht** [comment]
Another solution is to add the `ShowCardAndObtainEffect` for pot of greed to `topLevelEffectsQueue`
